In [1]:
from games.tictactoe import TicTacToe
from agents.agent_random import RandomAgent
from agents.minimax import MiniMax
from base.utils import play, run
import numpy as np

In [2]:
game = TicTacToe(render_mode='')

In [3]:
agents = dict(map(lambda agent: (agent, RandomAgent(game=game, agent=agent)), game.agents))
run(game=game, agents=agents)

({-1: 35, 0: 12, 1: 53}, 0.18)

In [4]:
agents[game.agents[0]] = MiniMax(game=game, agent=game.agents[0], depth=2)
run(game=game, agents=agents, N=1000)

AttributeError: 'raw_env' object has no attribute '_cumulative_rewards'

In [118]:
agents[game.agents[1]] = MiniMax(game=game, agent=game.agents[1], depth=2)
run(game=game, agents=agents, N=1000)

DEBUG:root:<class 'numpy.ndarray'>
DEBUG:root:[[0 0 0]
 [0 0 0]
 [0 0 0]]
DEBUG:root:(0, 0, 0, 0, 0, 0, 0, 0, 0)
DEBUG:root:Policy: [0.11111111 0.11111111 0.11111111 0.11111111 0.11111111 0.11111111
 0.11111111 0.11111111 0.11111111]
DEBUG:root:Legal moves: [0, 1, 2, 3, 4, 5, 6, 7, 8]
DEBUG:root:Legal move probabilities: [0.11111111 0.11111111 0.11111111 0.11111111 0.11111111 0.11111111
 0.11111111 0.11111111 0.11111111]
DEBUG:root:Chosen action: 0


AttributeError: 'raw_env' object has no attribute '_cumulative_rewards'

In [9]:
from agents.counterfactualregret import CounterFactualRegret
from importlib import reload
import agents
reload(agents)
reload(agents.counterfactualregret)
import games
from games.tictactoe import TicTacToe
from agents.agent_random import RandomAgent
from agents.minimax import MiniMax
from base.utils import play, run
import numpy as np



In [10]:
reload(agents.counterfactualregret)
from agents.counterfactualregret import CounterFactualRegret
reload(games.tictactoe)
from games.tictactoe import TicTacToe

game = TicTacToe(render_mode='')


In [11]:
game.observe('player_1')
game._cumulative_rewards

{'player_1': 0.0, 'player_2': 0.0}

In [12]:
agents = dict(map(lambda agent: (agent, CounterFactualRegret(game=game, agent=agent)), game.agents))

for agent in agents.values():
    agent.train(niter=100)  # You can adjust the number of iterations
    
run(game=game, agents=agents)

2023-11-01 20:42:26,796 - DEBUG - Training agent player_1
2023-11-01 20:42:26,802 - DEBUG - Node agent: player_1
2023-11-01 20:42:26,803 - DEBUG - Legal moves: [0, 1, 2, 3, 4, 5, 6, 7, 8]
2023-11-01 20:42:26,805 - DEBUG - Attempting action 0 in game state (0, 0, 0, 0, 0, 0, 0, 0, 0)
2023-11-01 20:42:26,806 - DEBUG - <class 'str'>
2023-11-01 20:42:26,807 - DEBUG - (2,)
2023-11-01 20:42:26,809 - DEBUG - 0.1111111111111111
2023-11-01 20:42:26,809 - DEBUG - 2
2023-11-01 20:42:26,811 - DEBUG - Current game state: TicTacToe
2023-11-01 20:42:26,812 - DEBUG - Action: 0
2023-11-01 20:42:26,814 - DEBUG - Legal moves: [0, 1, 2, 3, 4, 5, 6, 7, 8]


AttributeError: 'raw_env' object has no attribute '_cumulative_rewards'

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [14]:
game1 = TicTacToe(render_mode='')
game2 = game.clone()
print(id(game1), id(game2))  # Should print different IDs


2039950914416 2039924056912


In [59]:
from agents.counterfactualregret import CounterFactualRegret
from importlib import reload
import agents
reload(agents)
reload(agents.counterfactualregret)

from games.kuhn import KuhnPoker
from agents.agent_random import RandomAgent
from base.utils import play, run
import numpy as np

game = KuhnPoker(render_mode='human')
reload(agents.counterfactualregret)
from agents.counterfactualregret import CounterFactualRegret


In [60]:
agents = dict(map(lambda agent: (agent, CounterFactualRegret(game=game, agent=agent)), game.agents))

for agent in agents.values():
    agent.train(niter=100)  # You can adjust the number of iterations
    
run(game=game, agents=agents)

2023-10-29 19:28:17,284 - DEBUG - Training agent agent_0
2023-10-29 19:28:17,286 - DEBUG - Node agent: agent_0
2023-10-29 19:28:17,287 - DEBUG - Legal moves: [0, 1]
2023-10-29 19:28:17,288 - DEBUG - Attempting action 0 in game state 1
2023-10-29 19:28:17,289 - DEBUG - <class 'str'>
2023-10-29 19:28:17,290 - DEBUG - (2,)
2023-10-29 19:28:17,291 - DEBUG - 0.5
2023-10-29 19:28:17,291 - DEBUG - 2
2023-10-29 19:28:17,293 - DEBUG - Current game state: KuhnPoker
2023-10-29 19:28:17,294 - DEBUG - Action: 0
2023-10-29 19:28:17,294 - DEBUG - Legal moves: [0, 1]
2023-10-29 19:28:17,295 - DEBUG - Before recursive call, game state: KuhnPoker, attempting action: 0
2023-10-29 19:28:17,296 - DEBUG - Node agent: agent_1
2023-10-29 19:28:17,297 - DEBUG - Entering eval_node, game state: 2p
2023-10-29 19:28:17,298 - DEBUG - Legal moves: [0, 1]
2023-10-29 19:28:17,299 - DEBUG - Attempting action 0 in game state 2p
2023-10-29 19:28:17,300 - DEBUG - Node agent: agent_0
2023-10-29 19:28:17,301 - DEBUG - Befor

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [54]:
game.available_actions()

[0, 1]

In [55]:
game.reset()
game.step(1)
game.observe('agent_0')

'2b'